import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="font-wedding">Romulo e Júlia</h1>
      <h2>adasplp</h2>
      <h3>adasplp</h3>
      <p>adasplp</p>
    </div>
  );
};

export default Home;
